// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvEtXov5FIXiEZEfAslMSsuupmrEUKaj0',
    appId: '1:890687165161:web:46f172a27295cfe6b1d678',
    messagingSenderId: '890687165161',
    projectId: 'foomapp-a2cb5',
    authDomain: 'foomapp-a2cb5.firebaseapp.com',
    storageBucket: 'foomapp-a2cb5.firebasestorage.app',
    measurementId: 'G-TH7VTEJTCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCURImXKsUzs6R58dgIPUoUiHWX1A3ZXR8',
    appId: '1:890687165161:android:5853273a613008c2b1d678',
    messagingSenderId: '890687165161',
    projectId: 'foomapp-a2cb5',
    storageBucket: 'foomapp-a2cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj7IVaCi7ed77oFr1SOoH5GNkIUdcN4VQ',
    appId: '1:890687165161:ios:625d1842a96eeb3db1d678',
    messagingSenderId: '890687165161',
    projectId: 'foomapp-a2cb5',
    storageBucket: 'foomapp-a2cb5.firebasestorage.app',
    androidClientId: '890687165161-nfsg19f4gnh22uugfbgk6vasb5c05o5h.apps.googleusercontent.com',
    iosClientId: '890687165161-h7on6aiqus6o3hdlppmv5utkcjlh3ogn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj7IVaCi7ed77oFr1SOoH5GNkIUdcN4VQ',
    appId: '1:890687165161:ios:625d1842a96eeb3db1d678',
    messagingSenderId: '890687165161',
    projectId: 'foomapp-a2cb5',
    storageBucket: 'foomapp-a2cb5.firebasestorage.app',
    androidClientId: '890687165161-nfsg19f4gnh22uugfbgk6vasb5c05o5h.apps.googleusercontent.com',
    iosClientId: '890687165161-h7on6aiqus6o3hdlppmv5utkcjlh3ogn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvEtXov5FIXiEZEfAslMSsuupmrEUKaj0',
    appId: '1:890687165161:web:0b1a65f0139309d7b1d678',
    messagingSenderId: '890687165161',
    projectId: 'foomapp-a2cb5',
    authDomain: 'foomapp-a2cb5.firebaseapp.com',
    storageBucket: 'foomapp-a2cb5.firebasestorage.app',
    measurementId: 'G-JDVP210DKF',
  );
}
